### PR TITLE
add kale

### PR DESCRIPTION
**Pull request by alpaylan**
https://github.com/user-attachments/assets/70121567-ab44-4e51-b5bc-92821db0425c

https://github.com/user-attachments/assets/ac957069-111c-4b37-aada-114453e522cd

image

### CODE REVIEW

**Comment by awesomekling** [comment]
Please add it as a subdirectory like everyone else, not a submodule :)

**Comment by alpaylan** [comment]
Ah, I thought I had deleted the `.git` directory and then pushed. I don't know why that happened, will fix it now.

**Comment by alpaylan** [comment]
I think this should work?

**Comment by alpaylan** [comment]
Ah wait, I broke it..

**Pull request merged**
